---
title: "Covid 19 Time Series Data"
output: 
  html_document:
    code_folding: hide
   


date: "2023-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


#Load libraries
```{r}

library(data.table)
library(ggplot2)
library(tidyverse)
library(GGally) 

```



#Read in data
```{r}
#Free dataset from link below
#https://www.kaggle.com/datasets/niketchauhan/covid-19-time-series-data
dt <- read.table("time-series-19-covid-combined.csv",header=TRUE,sep=",",stringsAsFactors=FALSE)
setDT(dt)

dt
```

```{r}
glimpse(dt)
```


#Utility Functions
```{r}


#Temporary converts a datatable's character datatypes into factor. This way when summarize function is used, it lists out the counts of the characters.
factorize_str <- function (dt){
  #Making a copy to not affect the original datatable
  dt_copy <- copy(dt)

  for (col_name in colnames(dt_copy)){
    if (is.character(dt_copy[[col_name]])){
        set(dt_copy, j = col_name, value = as.factor(dt_copy[[col_name]]))
    }
  }

  #Another way of doing it
  # changeCols <- names(dt_copy)[sapply(dt_copy, is.character)]
  # dt_copy[,(changeCols):= lapply(.SD, as.factor), .SDcols = changeCols]
    
  dt_copy
}


summary(factorize_str(dt))
# Lots of empty values for column province.state .... 50,000/72,000 is approx 70%
```



```{r}

cat('There are ',dim(dt)[1] , "columns and ",dim(dt)[2], "rows.")

```


```{r}

character_columns <- c('Country.Region' , "Province.State")
number_columns <-c( 'Lat','Long','Confirmed','Recovered','Deaths')



dt[,Date:=ymd(Date)]
dt


nrow(dt)

#checking for percentage of nulls for each column
round(colSums(is.na(dt)) * 100/nrow(dt) ,1)

colSums(dt=="")


unique(dt[Province.State !="" , .(Country.Region,Province.State) ])

dt[, .N , by=c("Country.Region" , "Province.State")]





```
```{r}
#No recovery data for Canada only. Other countries don't have NA values for Recovery column
dt[is.na(Recovered)]
summary(factorize_str(dt[is.na(Recovered)]))
```



```{r}
#Date statistics

max(dt$Date)
min(dt$Date)
max(dt$Date)-min(dt$Date) #269 days is ~ 9 months



```

```{r}

country_events_data_dt <- dt[ , .(Country.Region ,Confirmed , Recovered,Deaths)]
country_events_data_dt

```




```{r}

# USA has the higher number of cases per month
country_events_data_dt [ , .(avg_case_per_month=as.integer(sum(Confirmed)/9)), by='Country.Region'][order(-avg_case_per_month)]

```


```{r}

country_events_data_dt [ , .(avg_case_per_month=as.integer(sum(Confirmed)/269)), by='Country.Region'][order(-avg_case_per_month)]
```



```{r}
summary(factorize_str(dt[is.na(Recovered)]))
```





#Analyzing Beijing, China
```{r}


china_beijing_dt <- dt[Country.Region =='China' & Province.State=='Beijing']


summary(factorize_str(china_beijing_dt))



china_beijing_dt[ , year_mon:= substring(format(Date, format = "%Y%m%d"),0,6)]
china_beijing_dt


china_beijing_agg_dt <- china_beijing_dt [, lapply(.SD, sum), .SDcols=c('Confirmed','Recovered','Deaths') ,by='year_mon']
china_beijing_agg_dt


china_beijing_agg_dt[ ,year_mon:=ym(year_mon)]
china_beijing_agg_dt


```

```{r}


num.cols <- sapply(china_beijing_agg_dt, is.numeric)
ggpairs( china_beijing_agg_dt[,..num.cols] )

```

```{r}

#

ggplot(data = china_beijing_agg_dt, mapping = aes(x = year_mon , y=Confirmed )) +
  geom_point() +
  geom_smooth(se = FALSE) +
  ggtitle("China Beijing Year 2020 Monthly Confirmed Cases") +
  labs(y = "Confirmed Cases", x = "month") +
  theme(plot.title = element_text(hjust = 0.5))

  
  

```


```{r}

colors <- c("Confirmed" = "blue", "Recovered" = "green")
ggplot() + geom_line(aes(x=china_beijing_agg_dt$year_mon,y=china_beijing_agg_dt$Confirmed,color='Confirmed')) + 
           geom_line(aes(x=china_beijing_agg_dt$year_mon,y=china_beijing_agg_dt$Recovered,color='Recovered')) + 
            labs(x = "Month",
                 y = "Events",
                 color = "Legend") + 
           ggtitle("China Beijing Year 2020 Monthly Confirmed/Recovered Events") +
           theme(plot.title = element_text(hjust = 0.5)) +
           scale_color_manual(values = colors)
```

```{r}

colors <- c("Confirmed" = "blue", "Recovered" = "green" , "Deaths"="red" )
ggplot() + geom_line(aes(x=china_beijing_agg_dt$year_mon,y=china_beijing_agg_dt$Confirmed,color='Confirmed')) + 
           geom_line(aes(x=china_beijing_agg_dt$year_mon,y=china_beijing_agg_dt$Recovered,color='Recovered')) + 
           geom_line(aes(x=china_beijing_agg_dt$year_mon,y=china_beijing_agg_dt$Deaths,color='Deaths')) +
            labs(x = "Month",
                 y = "Events",
                 color = "Legend") + 
           ggtitle("China Beijing Year 2020 Monthly Trio Events") +
           theme(plot.title = element_text(hjust = 0.5)) +
           scale_color_manual(values = colors)

```





```{r}


Australia_dt <- dt[Country.Region =='Australia' ]
Australia_dt

summary(factorize_str(Australia_dt))
```

```{r}


Australia_dt[ , year_mon:= substring(format(Date, format = "%Y%m%d"),0,6)]
Australia_dt


Australia_agg_dt <- Australia_dt [, lapply(.SD, sum), .SDcols=c('Confirmed','Recovered','Deaths') ,by='year_mon']
Australia_agg_dt


Australia_agg_dt[ ,year_mon:=ym(year_mon)]
Australia_agg_dt
```

```{r}

colors <- c("Confirmed" = "blue", "Recovered" = "green" , "Deaths"="red" )
ggplot() + geom_line(aes(x=Australia_agg_dt$year_mon,y=Australia_agg_dt$Confirmed,color='Confirmed')) + 
           geom_line(aes(x=Australia_agg_dt$year_mon,y=Australia_agg_dt$Recovered,color='Recovered')) + 
           geom_line(aes(x=Australia_agg_dt$year_mon,y=Australia_agg_dt$Deaths,color='Deaths')) +
            labs(x = "Month",
                 y = "Events",
                 color = "Legend") + 
           ggtitle("Australia Year 2020 Monthly Trio Events") +
           theme(plot.title = element_text(hjust = 0.5)) +
           scale_color_manual(values = colors)
```


